name: wine_test
channels:
  - conda-forge
dependencies:
  - ipython
  - numpy
  - requests
  - graphviz
  - ipykernel
  - scikit-learn
  - matplotlib
  - altair-all
  - plotly
  - python=3.12
  - panel
  - pandas
  - lightgbm
  - watchfiles
  - nb_conda_kernels
  - pip
  - pandera
  - jinja2
  - python-graphviz
  - deepchecks
  - vega_datasets
  - autograd
  - conda-lock
